<?php

namespace TripBundle\Repository;

/**
 * RestrictionTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionTripRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRestrictionsEmailsByTrip($trip)
    {
        $qb = $this
            ->createQueryBuilder('r')
            ->where('r.trip = :trip')
            ->setParameter('trip', $trip)
            ->select('r.email');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
