<?php

namespace TripBundle\Repository;

/**
 * RestrictionTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionTripRepository extends \Doctrine\ORM\EntityRepository
{

}
