<?php

namespace TripBundle\Repository;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends \Doctrine\ORM\EntityRepository
{
    private function userTripsWithRestrictionsQuery($user) {
        return $this
            ->createQueryBuilder('t')
            ->leftJoin('t.restrictions', 'rt')
            ->where('t.ouvert = true')
            ->orWhere('rt.email = :user_mail')
            ->andWhere('t.statut = :inscription')
            ->setParameter('user_mail', $user->getEmail())
            ->setParameter('inscription', 'Inscription');
    }

    public function getTripWithAdmins($id)
    {
        $qb = $this
            ->createQueryBuilder('t')
            ->where('t.id = :id')
            ->setParameter('id', $id)
            ->leftJoin('t.admins', 'a')
            ->addSelect('a');

        return $qb
            ->getQuery()
            ->getSingleResult();
    }

    public function getUserTripsWithRestrictions($user)
    {
        $qb = $this->userTripsWithRestrictionsQuery($user)
            ->addSelect('rt')
            ->orderBy('t.dateDebut');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function isTripAllowed($user, $trip)
    {
        $qb = $this->userTripsWithRestrictionsQuery($user)
            ->andWhere('t = :trip')
            ->setParameter('trip', $trip);

        return $qb
            ->getQuery()
            ->getOneOrNullResult() != null;
    }

}
