<?php

namespace TripBundle\Repository;

/**
 * TripParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserTripParticipantsWithTrips($user)
    {
        $qb = $this
            ->createQueryBuilder('tp')
            ->where('tp.participant = :user')
            ->setParameter('user', $user)
            ->leftJoin('tp.trip', 't')
            ->addSelect('t')
            ->orderBy('t.dateDebut');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getUserParticipant($user, $trip) {
        $qb = $this
            ->createQueryBuilder('tp')
            ->where('tp.participant = :user')
            ->andWhere('tp.trip = :trip')
            ->setParameter('user', $user)
            ->setParameter('trip', $trip);

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getTripsParticipantsWithUsersRestrictions($trip)
    {
        $qb = $this
                ->createQueryBuilder('tp')
                ->where('tp.trip = :trip')
                ->setParameter('trip', $trip)
                ->leftJoin('tp.participant', 'u')
                ->addSelect('u')
                ->orderBy('u.nom');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
